In [157]:
import sqlite3
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [1]:
df = pd.read_csv("tweet.csv", sep=";")

NameError: name 'pd' is not defined

In [158]:
try:
    connexion = sqlite3.connect("IMDB.db")
    c = connexion.cursor()
except:
    print("no db connexion")
    

with connexion:
    c.execute("UPDATE movies SET public = 'Tous publics' WHERE public = 'Tous Public';")
    print("ok")

ok

In [159]:
df = pd.read_sql("SELECT * FROM movies;", connexion)

In [160]:
df

,id,title,year,public,runtime,rating,total_rating,value,synopsis,img
0,1,Les Évadés,1994,Tous publics,142,9.3,2387274,28.34,Two imprisoned men bond over a number of years...,https://m.media-amazon.com/images/M/MV5BMDFkYT...
1,2,Le parrain,1972,12,175,9.2,1654566,134.97,An organized crime dynasty's aging patriarch t...,https://m.media-amazon.com/images/M/MV5BM2MyNj...
2,3,The Dark Knight : Le Chevalier noir,2008,Tous publics,152,9.0,2350355,534.86,When the menace known as the Joker wreaks havo...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
3,4,"Le parrain, 2ème partie",1974,Tous publics,202,9.0,1150887,57.30,The early life and career of Vito Corleone in ...,https://m.media-amazon.com/images/M/MV5BMWMwMG...
4,5,12 Hommes en colère,1957,Tous publics,96,9.0,704715,4.36,A jury holdout attempts to prevent a miscarria...,https://m.media-amazon.com/images/M/MV5BMWU4N2...
...,...,...,...,...,...,...,...,...,...,...
995,996,Diamants sur canapé,1961,Tous publics,115,7.6,169301,69.30,A young New York socialite becomes interested ...,https://m.media-amazon.com/images/M/MV5BNGEwMT...
996,997,Géant,1956,Tous publics,201,7.6,34697,4.69,Sprawling epic covering the life of a Texas ca...,https://m.media-amazon.com/images/M/MV5BODk3Yj...
997,998,Tant qu'il y aura des hommes,1953,Tous publics,118,7.6,44010,30.50,"In Hawaii in 1941, a private is cruelly punish...",https://m.media-amazon.com/images/M/MV5BM2U3Yz...
998,999,Lifeboat,1944,Tous publics,97,7.6,26857,6.85,Several survivors of a torpedoed merchant ship...,https://m.media-amazon.com/images/M/MV5BZTBmMj...
999,1000,Les 39 marches,1935,Tous publics,86,7.6,52888,2.88,A man in London tries to help a counter-espion...,https://m.media-amazon.com/images/M/MV5BMTY5OD...

In [161]:
#classer les mots par type
doc = nlp("Je travaille en France chez John Sena")
for ent in doc.ents:
    print(ent.text, ent.label_)

Je PERSON
France GPE
John Sena PERSON

In [162]:
#classer les mots par type
import spacy
from spacytextblob.spacytextblob import SpacyTextBlob

nlp = spacy.load('en_core_web_sm')
nlp.add_pipe('spacytextblob')


for i in list(df.values):
    doc = nlp(i[8])
    for ent in doc.ents:
        print(ent.text, ent.end_char, ent.label_)
    print('-'*100)

Two 3 CARDINAL
a number of years 46 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Joker 34 PERSON
one 105 CARDINAL
----------------------------------------------------------------------------------------------------
Vito Corleone 42 ORG
1920s 51 DATE
New York City 65 GPE
Michael 102 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Gandalf 7 ORG
Aragorn 19 ORG
the World of Men 41 ORG
Sauron 56 PERSON
Frodo 91 PERSON
Sam 99 PERSON
Mount Doom 127 LOC
----------------------------------------------------------------------------------------------------
two 16 CARDINAL
four 109 CARDINAL
----------------------------------------------------------------------------------------------------
German 9 NORP
Poland 25 GPE
World War II 45 EVENT
Oskar Schindler 76 PERSON
Jewish 119 NORP
Nazis 177 NORP
----------------------------------------------------------------------------------------------------
C.E.O. 152 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Hobbit 13 ORG
Shire 28 GPE
eight 38 CARDINAL
----------------------------------------------------------------------------------------------------
Kennedy 27 PERSON
Johnson 39 PERSON
the Vietnam War 56 EVENT
Watergate 71 EVENT
Alabama 149 GPE
75 170 DATE
----------------------------------------------------------------------------------------------------
two 31 CARDINAL
third 73 ORDINAL
----------------------------------------------------------------------------------------------------
Sam 19 PERSON
Mordor 41 PERSON
Gollum 76 PERSON
Sauron 129 ORG
Saruman 149 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Henry Hill 23 PERSON
Karen Hill 99 PERSON
Jimmy Conway 133 PERSON
Tommy DeVito 150 PERSON
Italian 165 NORP
----------------------------------------------------------------------------------------------------
Luke Skywalker 94 PERSON
Jedi 106 PERSON
Yoda 125 ORG
Darth Vader 171 PERSON
Boba Fett 207 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Greed 5 PERSON
Park 104 LOC
Kim 133 PERSON
----------------------------------------------------------------------------------------------------
Nedumaaran Rajangam 19 PERSON
Maara 26 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Rio 19 ORG
two 24 CARDINAL
one 51 CARDINAL
----------------------------------------------------------------------------------------------------
10-year-old 61 DATE
----------------------------------------------------------------------------------------------------
U.S. 48 GPE
----------------------------------------------------------------------------------------------------
one 52 CARDINAL
----------------------------------------------------------------------------------------------------
Jewish 26 NORP
Holocaust 80 EVENT
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
seven 79 CARDINAL
----------------------------------------------------------------------------------------------------
F.B.I. 14 ORG
----------------------------------------------------------------------------------------------------
Luke Skywalker 14 PERSON
a Jedi Knight 46 PERSON
Wookiee 72 ORG
two 80 CARDINAL
Empire 122 GPE
Princess Leia 203 PERSON
Darth Vader 235 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
seven 53 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
one 20 CARDINAL
America 31 GPE
first 69 ORDINAL
Treasury 95 ORG
Alexander Hamilton 115 PERSON
Broadway 142 FAC
Broadway 202 FAC
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
two 28 CARDINAL
----------------------------------------------------------------------------------------------------
Irish 101 NORP
South Boston 122 GPE
----------------------------------------------------------------------------------------------------
Polish 8 NORP
Jewish 15 NORP
Warsaw 75 GPE
World War II 98 EVENT
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
five 111 CARDINAL
----------------------------------------------------------------------------------------------------
12-year-old 23 DATE
Léon 61 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Sarah Connor 62 PERSON
ten year old 97 DATE
John Connor 114 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Japan 62 GPE
World War II 82 EVENT
----------------------------------------------------------------------------------------------------
Marty McFly 11 PERSON
17-year-old 26 DATE
thirty years 81 DATE
DeLorean 124 ORG
Doc Brown 188 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Phoenix 9 GPE
40,000 37 MONEY
----------------------------------------------------------------------------------------------------
American 29 NORP
Nazis 142 NORP
French 152 NORP
Morocco 160 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
five-year 25 DATE
12-year-old 69 DATE
----------------------------------------------------------------------------------------------------
Gotham City 14 GPE
Arthur Fleck 55 PERSON
Joker 230 LOC
----------------------------------------------------------------------------------------------------
1950 7 DATE
the Korean War 46 EVENT
Sergeant Süleyman 65 PERSON
----------------------------------------------------------------------------------------------------
Simon 58 PERSON
Vedha 104 ORG
Vikram 161 ORG
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
Singh Phogat 36 PERSON
two 48 CARDINAL
the Commonwealth Games 116 FAC
----------------------------------------------------------------------------------------------------
Miles Morales 18 PERSON
five 82 CARDINAL
----------------------------------------------------------------------------------------------------
Avengers 40 NORP
Infinity War (2018 60 EVENT
Avengers 136 NORP
Thanos 182 ORG
----------------------------------------------------------------------------------------------------
Thanos 106 NORP
----------------------------------------------------------------------------------------------------
Miguel 24 PERSON
the Land of the Dead 106 WORK_OF_ART
----------------------------------------------------------------------------------------------------
German 25 NORP
Mississippi 128 GPE
----------------------------------------------------------------------------------------------------
Eight years 11 DATE
Joker 27 ORG
Batman 54 PERSON
Catwoman 95 PERSON
Gotham City 141 GPE
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
eight-year-old 17 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
1984 7 DATE
East Berlin 19 GPE
----------------------------------------------------------------------------------------------------
fifteen years 54 DATE
Dae-Su 65 PERSON
five days 133 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Tatarigami 46 GPE
Ashitaka 64 PERSON
Tatara 136 PERSON
San 186 PERSON
the Mononoke Hime 205 PERSON
----------------------------------------------------------------------------------------------------

Prohibition-era 24 DATE
Jewish 31 NORP
the Lower East Side 71 LOC
Manhattan 84 GPE
thirty years later 108 DATE
----------------------------------------------------------------------------------------------------
1936 7 DATE
Indiana Jones 51 PERSON
U.S. 72 GPE
the Ark of the Covenant 115 ORG
Nazis 143 NORP
----------------------------------------------------------------------------------------------------
the winter 50 DATE
----------------------------------------------------------------------------------------------------
U.S. Army 11 ORG
Vietnam 38 GPE
Special Forces Colonel 101 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
a War Room 70 EVENT
----------------------------------------------------------------------------------------------------
British 17 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
one 106 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Jewish 70 NORP
----------------------------------------------------------------------------------------------------
April 6th, 1917 15 DATE
two 81 CARDINAL
1,600 167 CARDINAL
----------------------------------------------------------------------------------------------------
first 152 ORDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Iran 137 GPE
----------------------------------------------------------------------------------------------------
the Middle East 32 LOC
----------------------------------------------------------------------------------------------------
Dara 44 PERSON
Croatia 91 GPE
World War 2 110 EVENT
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Turkey 84 GPE
1980 92 DATE
----------------------------------------------------------------------------------------------------
Nazi 7 NORP
France 23 GPE
World War II 43 EVENT
Nazi 71 NORP
Jewish 100 NORP
U.S. 105 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Paris 45 GPE
----------------------------------------------------------------------------------------------------
Russian 60 NORP
Jewish 120 NORP
----------------------------------------------------------------------------------------------------
four 32 CARDINAL
Coney Island 45 LOC
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
M.I.T. 33 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Scottish 8 NORP
William Wallace 32 PERSON
----------------------------------------------------------------------------------------------------
one 98 CARDINAL
----------------------------------------------------------------------------------------------------
U.S. Marine 23 ORG
the Vietnam War 73 EVENT
Hue 174 GPE
----------------------------------------------------------------------------------------------------
Soviet 56 NORP
German 100 NORP
World War II 151 EVENT
----------------------------------------------------------------------------------------------------
Fifty-seven years 17 DATE
Officer Ripley 124 PERSON
----------------------------------------------------------------------------------------------------
Wolfgang Amadeus Mozart 57 PERSON
Antonio Salieri 85 PERSON
Mozart 150 PERSON
----------------------------------------------------------------------------------------------------
1980 7 DATE
Miami 13 GPE
Cuban 33 NORP
----------------------------------------------------------------------------------------------------
Han Solo 41 ORG
Rebels 73 NORP
Death Star 124 WORK_OF_ART
Luke 141 PERSON
Darth Vader 171 PERSON
----------------------------------------------------------------------------------------------------
WWII 34 EVENT
German 41 NORP
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
H.A.L. 9000 174 PRODUCT
----------------------------------------------------------------------------------------------------
T.E. Lawrence 26 PERSON
English 39 NORP
Arab 112 NORP
World War I 138 EVENT
Turks 166 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
New York City 15 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Italy 17 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Charles Foster Kane 60 PERSON
----------------------------------------------------------------------------------------------------
German 27 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Tramp 9 ORG
----------------------------------------------------------------------------------------------------
Anirudh 32 ORG
days 115 DATE
----------------------------------------------------------------------------------------------------
Indian 6 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
the 1970s 12 DATE
----------------------------------------------------------------------------------------------------
Italian 23 NORP
African-American 82 NORP
1960s 138 DATE
American South 153 LOC
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Bahubali 31 NORP
the Mahishmati Kingdom 171 LOC
----------------------------------------------------------------------------------------------------
Smeerensburg 98 ORG
Jesper 120 ORG
Klaus 146 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Delhi 7 GPE
----------------------------------------------------------------------------------------------------
1992 7 DATE
Abkhazia 30 GPE
Georgia 61 GPE
Estonian 74 NORP
----------------------------------------------------------------------------------------------------
Milkha Singh 46 PERSON
India 83 GPE
Pakistan 92 GPE
----------------------------------------------------------------------------------------------------
Sultan 22 GPE
Shahid Khan 38 PERSON
Khan 69 PERSON
Wasseypur 84 GPE
three 132 CARDINAL
----------------------------------------------------------------------------------------------------
16-year old 39 DATE
----------------------------------------------------------------------------------------------------
Paan Singh Tomar 29 PERSON
Indian 40 NORP
seven 58 CARDINAL
Chambal Valley 155 LOC
----------------------------------------------------------------------------------------------------
Three 5 CARDINAL
one 74 CARDINAL
----------------------------------------------------------------------------------------------------
one 71 CARDINAL
decades later 205 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
1954 7 DATE
U.S. 15 GPE
----------------------------------------------------------------------------------------------------
78-year-old 11 DATE
Carl Fredricksen 28 PERSON
Paradise Falls 54 PERSON
----------------------------------------------------------------------------------------------------
six year old 107 DATE
2013 162 DATE

Korean 169 NORP
7 177 CARDINAL
2013 205 DATE
----------------------------------------------------------------------------------------------------
Jordan Belfort 41 PERSON
----------------------------------------------------------------------------------------------------
Kabir Khan 10 PERSON
the Indian Women's National Hockey Team 66 ORG
----------------------------------------------------------------------------------------------------
the early days 116 DATE
----------------------------------------------------------------------------------------------------
the Falangist Spain 22 LOC
1944 30 DATE
----------------------------------------------------------------------------------------------------
Andy 93 PERSON
----------------------------------------------------------------------------------------------------
British 19 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Batman 38 PERSON
Gotham City 88 GPE
----------------------------------------------------------------------------------------------------
Indian 19 NORP
Indian 50 NORP
America 87 GPE
----------------------------------------------------------------------------------------------------
Traudl Junge 12 PERSON
Adolf Hitler 50 ORG
Nazi 69 NORP
Berlin 105 GPE
the end of WWII 131 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
John Nash 15 PERSON
----------------------------------------------------------------------------------------------------
Three 5 CARDINAL
----------------------------------------------------------------------------------------------------
three 24 CARDINAL
Hatchet Harry 114 PERSON
Harry 145 PERSON
a week 162 DATE
500,000 pounds 189 QUANTITY
----------------------------------------------------------------------------------------------------
1950s 28 DATE
Los Angeles 40 GPE
three 47 CARDINAL
one 81 CARDINAL
one 97 CARDINAL
----------------------------------------------------------------------------------------------------
Bandit 16 LOC
35 years 53 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
two 70 CARDINAL
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
Retired Old West 16 PERSON
William Munny 41 PERSON
one 66 CARDINAL
Ned Logan 119 PERSON
The "Schofield Kid 155 WORK_OF_ART
----------------------------------------------------------------------------------------------------
1938 7 DATE
Henry Jones 47 PERSON
the Holy Grail 95 WORK_OF_ART
Henry " 114 PERSON
Indiana 121 GPE
Jones, Jr. 133 WORK_OF_ART
Adolf Hitler's 173 ORG
Nazis 179 NORP
----------------------------------------------------------------------------------------------------
Sarajevo 53 GPE
Italy 66 GPE
Perhan 74 GPE
Romany 100 PERSON
----------------------------------------------------------------------------------------------------
two 8 CARDINAL
----------------------------------------------------------------------------------------------------
German 81 NORP
Christmas 111 DATE
the Nakatomi Plaza 139 FAC
Los Angeles 154 GPE
----------------------------------------------------------------------------------------------------
Medieval 11 GPE
three 83 CARDINAL
----------------------------------------------------------------------------------------------------
Jake LaMotta 30 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
New York City 77 GPE
----------------------------------------------------------------------------------------------------
Prophet Muhammad 76 PERSON
Islamic 123 NORP
----------------------------------------------------------------------------------------------------
two 116 CARDINAL
----------------------------------------------------------------------------------------------------
Arthur 11 PERSON
Knights of the Round Table 46 ORG
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
Western 75 NORP
----------------------------------------------------------------------------------------------------
several hundred 48 CARDINAL
German 88 NORP
World War II 113 EVENT
----------------------------------------------------------------------------------------------------
Atticus Finch 13 ORG
Depression-era 45 DATE
South 51 LOC
----------------------------------------------------------------------------------------------------
two 45 CARDINAL
----------------------------------------------------------------------------------------------------
1948 7 DATE
American 20 NORP
Germany 46 GPE
four 57 CARDINAL
Nazis 63 NORP
----------------------------------------------------------------------------------------------------
two 9 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
the Black Plague 129 EVENT
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Broadway 102 FAC
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
Americans 13 NORP
Mexico 42 GPE
the Sierra Madre Mountains 126 FAC
----------------------------------------------------------------------------------------------------
Nazi 15 NORP
Poland 36 GPE
Polish 84 NORP
German 125 NORP
----------------------------------------------------------------------------------------------------
Klondike 33 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Brittany 33 GPE
the end of the eighteenth century 70 DATE
----------------------------------------------------------------------------------------------------
three 10 CARDINAL
----------------------------------------------------------------------------------------------------
Years later 119 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
less than three hours 103 TIME
----------------------------------------------------------------------------------------------------
Japanese 46 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Kashmir 30 LOC
----------------------------------------------------------------------------------------------------
Logan 72 PERSON
Laura 107 PERSON
----------------------------------------------------------------------------------------------------
7 years 24 DATE
first 163 ORDINAL
----------------------------------------------------------------------------------------------------
Six 3 CARDINAL
----------------------------------------------------------------------------------------------------
New York 47 GPE
Earth 123 LOC
----------------------------------------------------------------------------------------------------
Turkish 46 NORP
----------------------------------------------------------------------------------------------------
Earth 17 LOC
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
World War II American Army Medic Desmond T. Doss 48 EVENT
the Battle of Okinawa 89 FAC
first 136 ORDINAL
American 152 NORP
----------------------------------------------------------------------------------------------------
Riley 17 PERSON
Midwest 46 LOC
San Francisco 78 GPE
----------------------------------------------------------------------------------------------------
Three 5 CARDINAL
----------------------------------------------------------------------------------------------------
United States 31 GPE
Solomon Northup 48 PERSON
New York 88 GPE
----------------------------------------------------------------------------------------------------
1970s 19 DATE
Formula 43 ORG
James Hunt 65 PERSON
Niki Lauda 80 ORG
----------------------------------------------------------------------------------------------------
American 8 NORP
Carroll Shelby 36 PERSON
Ken Miles 57 PERSON
Ford 154 ORG
Ferrari 181 PERSON
the 24 Hours 197 TIME
Mans 208 NORP
1966 216 DATE
----------------------------------------------------------------------------------------------------
the Boston Globe 38 ORG
Catholic Archdiocese 140 ORG
Catholic Church 176 ORG
----------------------------------------------------------------------------------------------------
Ben 3 PERSON
Irish 18 NORP
----------------------------------------------------------------------------------------------------

London 71 GPE
Kolkata 82 GPE
----------------------------------------------------------------------------------------------------
Keller Dover's 19 PERSON
----------------------------------------------------------------------------------------------------
Max 193 PERSON
----------------------------------------------------------------------------------------------------
the most astounding day 66 DATE
Wednesday 194 DATE
----------------------------------------------------------------------------------------------------
Superman 29 PERSON
Bruce Wayne 79 PERSON
Diana Prince 111 PERSON
----------------------------------------------------------------------------------------------------
Korean War 22 EVENT
Walt Kowalski 44 PERSON
Thao Lor 86 PERSON
Hmong 95 GPE
Kowalski 132 PERSON
1972 160 DATE
Gran Torino 172 PERSON
----------------------------------------------------------------------------------------------------
Harry 5 PERSON
Ron 10 PERSON
Voldemort 45 PERSON
Horcruxes 67 PERSON
Hogwarts 149 PRODUCT
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
two 32 CARDINAL
eight-year-old 82 DATE
Melbourne 122 GPE
Max 131 PERSON
forty-four-year old 154 CARDINAL
New York 193 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Emory University 38 ORG
Christopher 75 PERSON
24,000 137 MONEY
Alaska 189 GPE
Christopher 243 PERSON
----------------------------------------------------------------------------------------------------
more than two million dollars 111 MONEY
the Rio Grande 139 LOC
----------------------------------------------------------------------------------------------------
Tokyo 16 GPE
twelve-year-old 43 DATE
----------------------------------------------------------------------------------------------------
six 16 CARDINAL
Indians 30 NORP
English 52 LANGUAGE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Paul Rusesabagina 17 PERSON
Tutsi 64 ORG
Hutu 112 PERSON
Rwanda 130 GPE
Africa 138 LOC
----------------------------------------------------------------------------------------------------
two 8 CARDINAL
the Korean War 55 EVENT
----------------------------------------------------------------------------------------------------
Nine years 10 DATE
Jesse 22 PERSON
Celine 33 ORG
first 39 ORDINAL
French 90 NORP
Jesse 103 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Korean 17 NORP
1986 34 DATE
two 39 CARDINAL
----------------------------------------------------------------------------------------------------
Three 5 CARDINAL
----------------------------------------------------------------------------------------------------
four-year 32 DATE
----------------------------------------------------------------------------------------------------
the Great Barrier Reef 51 FAC
Sydney 71 GPE
----------------------------------------------------------------------------------------------------
21 9 CARDINAL
Frank 20 PERSON
FBI 90 ORG
Carl 101 PERSON
----------------------------------------------------------------------------------------------------
three 38 CARDINAL
----------------------------------------------------------------------------------------------------
two 165 CARDINAL
----------------------------------------------------------------------------------------------------
1995 75 DATE
----------------------------------------------------------------------------------------------------
Victorian India 48 ORG
British 119 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
1900 30 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Matko 5 ORG
Matko 177 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
Renton 6 ORG
Edinburgh 40 ORG
----------------------------------------------------------------------------------------------------
Jerry Lundegaard's 18 PERSON
Marge Gunderson 150 PERSON
----------------------------------------------------------------------------------------------------
Serbian 18 NORP
----------------------------------------------------------------------------------------------------
24 hours 8 TIME
three 30 CARDINAL
French 54 NORP
the day 70 DATE
----------------------------------------------------------------------------------------------------
Simran 21 PERSON
Europe 31 LOC
first 55 ORDINAL
Simran 77 PERSON
India 92 GPE
----------------------------------------------------------------------------------------------------
Europe 47 LOC
one evening 81 TIME
Vienna 100 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
Hong Kong 24 GPE
one 52 CARDINAL
late-night 161 TIME
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
I.R.A. 39 NORP
English 127 NORP
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
Peking 51 GPE
1924 59 DATE
nearly 70 years 113 DATE
China 173 GPE
----------------------------------------------------------------------------------------------------
fourth 32 ORDINAL
----------------------------------------------------------------------------------------------------
Maverick 8 PERSON
John Keating 29 PERSON
----------------------------------------------------------------------------------------------------
one 22 CARDINAL
----------------------------------------------------------------------------------------------------
Chris Taylor 12 PERSON
Vietnam 43 GPE
two 98 CARDINAL
one 113 CARDINAL
----------------------------------------------------------------------------------------------------
World War III 28 EVENT
----------------------------------------------------------------------------------------------------
Travis Henderson 16 PERSON
four years 72 DATE
----------------------------------------------------------------------------------------------------
two 75 CARDINAL
----------------------------------------------------------------------------------------------------
Antarctica 29 LOC
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Brian Sweeney Fitzgerald 37 PERSON
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
Swedish 17 NORP
Ekdahls 98 GPE
----------------------------------------------------------------------------------------------------
four 45 CARDINAL
Earth 110 LOC
----------------------------------------------------------------------------------------------------
Victorian 11 NORP
----------------------------------------------------------------------------------------------------
Christmas 30 DATE
Brian 77 PERSON
----------------------------------------------------------------------------------------------------
U.S. 53 GPE
Vietnam War 65 EVENT
Pennsylvania 149 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Irish 8 NORP
18th-century 114 DATE
England 122 GPE
----------------------------------------------------------------------------------------------------
Russian 161 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
the Great Depression 27 EVENT
two 126 CARDINAL
----------------------------------------------------------------------------------------------------
early twentieth-century 55 DATE
Sweden 62 GPE
two 84 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Jef Costello 38 PERSON
----------------------------------------------------------------------------------------------------
Southern 20 NORP
two years 50 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
fifteenth-century 56 DATE
Russian 64 NORP
----------------------------------------------------------------------------------------------------
the 1950s 12 DATE
Algiers 65 LOC
French 104 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------

Hollywood 78 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
WWII 11 EVENT
Soviet 19 NORP
Ivan Bondarev 40 PERSON
three 75 CARDINAL
Soviet 94 NORP
German 146 NORP
----------------------------------------------------------------------------------------------------
only one 134 CARDINAL
----------------------------------------------------------------------------------------------------
1925 33 DATE
two 38 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Jewish 14 NORP
----------------------------------------------------------------------------------------------------
two 18 CARDINAL
----------------------------------------------------------------------------------------------------
Rome 48 GPE
----------------------------------------------------------------------------------------------------
Spider 119 PERSON
----------------------------------------------------------------------------------------------------
British 7 NORP
Kwai 71 PERSON
Japanese 90 NORP
----------------------------------------------------------------------------------------------------
Four 4 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
South American 28 NORP
four 42 CARDINAL
----------------------------------------------------------------------------------------------------
Albuquerque 76 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Holly Martins 27 PERSON
Vienna 62 GPE
Harry Lime 148 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
first 124 ORDINAL
----------------------------------------------------------------------------------------------------
United States 63 GPE
Senate 70 ORG
----------------------------------------------------------------------------------------------------
the American Civil War 96 EVENT
----------------------------------------------------------------------------------------------------
WWI 10 ORG
two 15 CARDINAL
French 22 NORP
German 71 NORP
----------------------------------------------------------------------------------------------------
New York 80 GPE
one 153 CARDINAL
----------------------------------------------------------------------------------------------------
1431 7 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Hypnotist 9 ORG
Caligari 22 PERSON
Cesare 50 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Togo 17 PERSON
1925 48 DATE
----------------------------------------------------------------------------------------------------
Iraq 9 GPE
Kuwait 24 GPE
August 1990 39 DATE
Indian 57 NORP
more than 170,000 116 CARDINAL
----------------------------------------------------------------------------------------------------
Indian 9 NORP
Pakistani 67 NORP
----------------------------------------------------------------------------------------------------
India 229 GPE
----------------------------------------------------------------------------------------------------
Los Angeles 45 GPE
----------------------------------------------------------------------------------------------------
five-year-old 15 DATE
Indian 22 NORP
Australian 54 NORP
hundreds of kilometers 103 QUANTITY
25 years later 129 DATE
----------------------------------------------------------------------------------------------------
Mars 37 LOC
Earth 133 LOC
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
India 16 GPE
decades 77 DATE
two 98 CARDINAL
----------------------------------------------------------------------------------------------------
Found 5 GPE
----------------------------------------------------------------------------------------------------
the New York Times 27 ORG
August 114 DATE
fifth 174 ORDINAL
first 236 ORDINAL
----------------------------------------------------------------------------------------------------
Mumbai 68 GPE
----------------------------------------------------------------------------------------------------
C.B.I 83 ORG
----------------------------------------------------------------------------------------------------
20 4 CARDINAL
----------------------------------------------------------------------------------------------------
first 33 ORDINAL
Rama 44 LOC
Jakarta 86 GPE
----------------------------------------------------------------------------------------------------
World War II 19 EVENT
English 32 NORP
Alan Turing 64 PERSON
Enigma 97 PRODUCT
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
K 20 ORG
Blade Runner 100 PERSON
Rick Deckard 113 PERSON
thirty years 150 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
British 34 NORP
Freddie Mercury 82 ORG
Live Aid 134 ORG
1985 140 DATE
----------------------------------------------------------------------------------------------------
the 1820s 55 DATE
----------------------------------------------------------------------------------------------------
two 53 CARDINAL
----------------------------------------------------------------------------------------------------
Rio de Janeiro 101 GPE
----------------------------------------------------------------------------------------------------
King George VI 27 ORG
the British Empire 88 GPE
1936 96 DATE
----------------------------------------------------------------------------------------------------
the 1960s 64 DATE
African American 119 NORP
daily 228 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Iran 91 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Japanese 19 NORP
China 37 GPE
Ip Man 172 PERSON
----------------------------------------------------------------------------------------------------
Indian Muslim 16 NORP
Asperger 34 PERSON
the United States 110 GPE
----------------------------------------------------------------------------------------------------
40 11 CARDINAL
Turkish 23 NORP
----------------------------------------------------------------------------------------------------
Mumbai 8 GPE
Indian 84 NORP
Millionaire 126 ORG
----------------------------------------------------------------------------------------------------
Tchaikovsky 110 GPE
Swan Lake 123 WORK_OF_ART
----------------------------------------------------------------------------------------------------
1997 7 DATE
Rio de Janeiro 22 PERSON
Nascimento 42 PERSON
----------------------------------------------------------------------------------------------------
Earth 5 LOC
Loki 119 PERSON
----------------------------------------------------------------------------------------------------
Iranian 34 NORP
the Islamic Revolution 78 EVENT
----------------------------------------------------------------------------------------------------

1985 7 DATE
Dallas 14 GPE
Ron Woodroof 52 PERSON
----------------------------------------------------------------------------------------------------
Munna Bhai 10 PERSON
Mahatma Gandhi 51 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Jason Bourne 12 PERSON
----------------------------------------------------------------------------------------------------
a few days 107 DATE
----------------------------------------------------------------------------------------------------
Basin City 61 GPE
three 87 CARDINAL
----------------------------------------------------------------------------------------------------
Elle 22 ORG
Jean-Dominique Bauby 50 PERSON
----------------------------------------------------------------------------------------------------
Turk 18 PERSON
G.O.R.A. 157 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
00 16 CARDINAL
James Bond 70 PERSON
first 92 ORDINAL
007 107 CARDINAL
Casino Royale 209 ORG
Montenegro 221 GPE
----------------------------------------------------------------------------------------------------
Bill 81 PERSON
Budd 109 PERSON
one 135 CARDINAL
Elle 145 ORG
----------------------------------------------------------------------------------------------------
Russian 14 NORP
two 30 CARDINAL
----------------------------------------------------------------------------------------------------
Buddhist 29 NORP
----------------------------------------------------------------------------------------------------
Spaniard 29 NORP
Ramon Sampedro 44 PERSON
thirty-year 70 DATE
----------------------------------------------------------------------------------------------------
James J. Braddock 30 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Blacksmith 10 PERSON
Jack Sparrow 76 PERSON
Jack 129 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Seoul 97 GPE
----------------------------------------------------------------------------------------------------
Colorado 75 GPE
----------------------------------------------------------------------------------------------------
Anatolian 39 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
the San Fernando Valley 112 LOC
----------------------------------------------------------------------------------------------------
East European 16 NORP
the United States 50 GPE
Hollywood 106 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
60th 15 ORDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
Karl Childers 13 PERSON
----------------------------------------------------------------------------------------------------
East London 194 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Puppet 92 PRODUCT
----------------------------------------------------------------------------------------------------
Jack Skellington 16 PERSON
Christmas Town 66 ORG
Christmas 103 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Jimmy Santiago Baca 62 PERSON
Paco 102 PERSON
Cruz 111 PERSON
Miklo 145 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Grand Vizier 59 ORG
----------------------------------------------------------------------------------------------------
New Orleans 11 GPE
Jim Garrison 42 PERSON
Kennedy 80 PERSON
----------------------------------------------------------------------------------------------------
his days 33 DATE
----------------------------------------------------------------------------------------------------
John Dunbar 22 PERSON
Civil War 62 EVENT
Indians 100 NORP
----------------------------------------------------------------------------------------------------
the hottest day of the year 30 DATE
Brooklyn 88 GPE
----------------------------------------------------------------------------------------------------
Selfish 7 NORP
Charlie Babbitt's 32 PERSON
Raymond 84 PERSON
Charlie 110 PERSON
----------------------------------------------------------------------------------------------------
Neo-Tokyo 45 ORG
two 146 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
French 8 NORP
World War II 77 EVENT
first 179 ORDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
2029 to 1984 41 DATE
the same year 122 DATE
----------------------------------------------------------------------------------------------------
Indian 64 NORP
British 92 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Washington 125 GPE
----------------------------------------------------------------------------------------------------
Alvy Singer 11 ORG
Jewish 30 NORP
Annie Hall 94 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Three 5 CARDINAL
----------------------------------------------------------------------------------------------------
American 11 NORP
Transylvania 152 GPE
----------------------------------------------------------------------------------------------------
two 44 CARDINAL
----------------------------------------------------------------------------------------------------
12-year-old 18 DATE
two 93 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
1951 7 DATE
North Texas 90 LOC
----------------------------------------------------------------------------------------------------
Russia 26 GPE
Jewish 36 NORP
three 77 CARDINAL
anti-Semitic 121 NORP
----------------------------------------------------------------------------------------------------
Italian 21 NORP
----------------------------------------------------------------------------------------------------
Wyoming 7 GPE
early 1900s 20 DATE
Butch Cassidy 35 PERSON
Bolivia 228 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
a distressing night 170 TIME
----------------------------------------------------------------------------------------------------
Austrian 26 NORP
Naval 83 GPE
----------------------------------------------------------------------------------------------------
Russian 21 NORP
World War I 165 EVENT
the October Revolution 197 EVENT
----------------------------------------------------------------------------------------------------
two 32 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Twelve 6 CARDINAL
Parisian 47 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
a week 36 DATE
Rome 100 GPE
----------------------------------------------------------------------------------------------------
American 36 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Mexican 81 NORP
----------------------------------------------------------------------------------------------------

Brick 5 PERSON
his days 60 DATE
----------------------------------------------------------------------------------------------------
Broadway 31 FAC
J.J. Hunsecker 56 PERSON
Sidney Falco 102 PERSON
----------------------------------------------------------------------------------------------------
Crook Johnny Clay 17 PERSON
five 34 CARDINAL
----------------------------------------------------------------------------------------------------
10,000 130 MONEY
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
two 8 CARDINAL
American World War II 39 ORG
German 72 NORP
J.J. Sefton 122 PERSON
----------------------------------------------------------------------------------------------------
American 87 NORP
Rome 103 GPE
----------------------------------------------------------------------------------------------------
New Orleans 64 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
the Duke D'Ascoyne 45 ORG
eight 95 CARDINAL
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Three 5 CARDINAL
World War II 18 EVENT
America 61 GPE
----------------------------------------------------------------------------------------------------
three 64 CARDINAL
----------------------------------------------------------------------------------------------------
Midwest 14 LOC
California 73 GPE
the Great Depression 140 EVENT
----------------------------------------------------------------------------------------------------
Dorothy Gale 12 PERSON
Kansas 48 GPE
Wizard 147 PERSON
Kansas 186 GPE
----------------------------------------------------------------------------------------------------
France 26 GPE
World War II 55 EVENT
French 112 NORP
----------------------------------------------------------------------------------------------------
German 8 NORP
World War I 41 EVENT
----------------------------------------------------------------------------------------------------
the Russian Revolution of 1905 46 EVENT
Potemkin 83 ORG
Odessa 199 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Baumbach 13 PERSON
----------------------------------------------------------------------------------------------------
1980s 8 DATE
Italy 14 GPE
seventeen-year-old 61 DATE
----------------------------------------------------------------------------------------------------
59-year-old 51 DATE
Employment and Support Allowance 163 ORG
----------------------------------------------------------------------------------------------------
Japan 12 GPE
Isle of Dogs 26 ORG
----------------------------------------------------------------------------------------------------
New Zealand 110 GPE
----------------------------------------------------------------------------------------------------
the Pacific Northwest 39 ORG
six 76 CARDINAL
----------------------------------------------------------------------------------------------------
Dublin 26 GPE
the 1980s 43 DATE
----------------------------------------------------------------------------------------------------
Sakaar 31 PERSON
Thor 37 GPE
Ragnarök 98 PERSON
Hela 184 PERSON
----------------------------------------------------------------------------------------------------
Hitler 21 PERSON
Jewish 68 NORP
----------------------------------------------------------------------------------------------------
twelve 83 CARDINAL
----------------------------------------------------------------------------------------------------
Rey 40 PERSON
Finn 70 PERSON
Han Solo 110 NORP
Chewbacca 124 GPE
----------------------------------------------------------------------------------------------------
Jesse 13 PERSON
nine years 35 DATE
Greece 48 GPE
Almost two decades 68 DATE
first 98 ORDINAL
Vienna 137 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Anatolian 64 NORP
----------------------------------------------------------------------------------------------------
Hollywood 102 GPE
----------------------------------------------------------------------------------------------------
the same day 53 DATE
----------------------------------------------------------------------------------------------------
Anne 16 PERSON
Britain 139 GPE
Anne 170 PERSON
----------------------------------------------------------------------------------------------------
Algerian 16 NORP
French 40 NORP
----------------------------------------------------------------------------------------------------
Astronaut Sam Bell 18 PERSON
three-year 93 DATE
Moon 111 PERSON
GERTY 160 ORG
Earth 181 LOC
----------------------------------------------------------------------------------------------------
Oskar 5 PERSON
Eli 72 ORG
----------------------------------------------------------------------------------------------------
Earth 94 LOC
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Mason 17 ORG
----------------------------------------------------------------------------------------------------
1980s 68 DATE
Romania 76 GPE
----------------------------------------------------------------------------------------------------
James T. Kirk 23 PERSON
Spock 78 PERSON
Romulan 121 PERSON
one 187 CARDINAL
----------------------------------------------------------------------------------------------------
Ray 49 PERSON
Bruges 113 GPE
Belgium 122 GPE
Ray 155 PERSON
----------------------------------------------------------------------------------------------------
John Oldman 52 PERSON
----------------------------------------------------------------------------------------------------
Iwo Jima 35 GPE
the United States 61 GPE
Imperial Japan 80 ORG
World War II 100 EVENT
Japanese 146 NORP
----------------------------------------------------------------------------------------------------
Los Angeles 51 GPE
five 164 CARDINAL
----------------------------------------------------------------------------------------------------
Bengal 194 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
French-Canadian 23 NORP
the 1960s 48 DATE
1970s 58 DATE
Catholic 168 NORP
----------------------------------------------------------------------------------------------------
Christmas Eve 16 DATE
three 23 CARDINAL
Tokyo 70 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Afghan 37 NORP
Tony Stark 75 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Aman 84 PERSON
Aman 94 PERSON
Rohit 184 ORG
Naina 191 GPE
----------------------------------------------------------------------------------------------------
forty-year-old 150 DATE
----------------------------------------------------------------------------------------------------
three 18 CARDINAL
one 72 CARDINAL
----------------------------------------------------------------------------------------------------
Harry Potter 12 PERSON
Ron 17 PERSON
Hogwarts School of Witchcraft 70 ORG
Wizardry 83 PERSON
their third year 104 DATE
----------------------------------------------------------------------------------------------------
Nameless 27 ORG
the King of Qin 60 WORK_OF_ART
three 103 CARDINAL
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
two 55 CARDINAL
----------------------------------------------------------------------------------------------------
Bosnia and Herzegovina 22 GPE
1993 34 DATE
two 87 CARDINAL
Two 106 CARDINAL
third 215 ORDINAL
----------------------------------------------------------------------------------------------------
Bebop 97 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
nine 109 CARDINAL
----------------------------------------------------------------------------------------------------
2027 7 DATE
----------------------------------------------------------------------------------------------------
Rolling Stone Magazine 81 ORG
----------------------------------------------------------------------------------------------------
Mulholland Drive 49 FAC
Hollywood 101 GPE
Los Angeles 157 GPE
----------------------------------------------------------------------------------------------------
Woody 10 PERSON
Buzz 45 PERSON
Woody 103 PERSON
Jessie 172 PERSON
Bullseye 198 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Maori 29 GPE
----------------------------------------------------------------------------------------------------
Detroit 10 GPE
Hollywood 122 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
Puerto Rican 14 NORP
N.Y.C. 181 ORG
----------------------------------------------------------------------------------------------------
one day 115 DATE
----------------------------------------------------------------------------------------------------
Christy Brown 13 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
the era of Prohibition 29 DATE
the United States 50 GPE
Chicago 110 GPE
Al Capone 129 PERSON
----------------------------------------------------------------------------------------------------
two 11 CARDINAL
two years 35 DATE
Hannah 49 PERSON
Lee 93 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Spinal Tap 10 ORG
England 26 GPE
Marty DiBergi 88 PERSON
----------------------------------------------------------------------------------------------------
the 1940s 12 DATE
Ralphie 39 PERSON
Santa 95 GPE
Christmas 151 DATE
----------------------------------------------------------------------------------------------------
Jake Blues 10 PERSON
Catholic 86 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Bob Fosse 32 PERSON
Joe Gideon 103 PERSON
----------------------------------------------------------------------------------------------------
two 80 CARDINAL
Philadelphia 93 GPE
----------------------------------------------------------------------------------------------------
The Washington Post 20 ORG
Bob Woodward 44 PERSON
Carl Bernstein 63 PERSON
the Watergate 100 EVENT
Richard Nixon 146 PERSON
----------------------------------------------------------------------------------------------------
seven 92 CARDINAL
the Holy Mountain 135 LOC
----------------------------------------------------------------------------------------------------
1930s 58 DATE
Italian 66 NORP
----------------------------------------------------------------------------------------------------
six 66 CARDINAL
----------------------------------------------------------------------------------------------------
the 16th century 19 DATE
Don Lope de Aguirre 64 PERSON
Spanish 80 NORP
El Dorado 114 GPE
----------------------------------------------------------------------------------------------------
Harold 44 PERSON
Maude 116 PERSON
----------------------------------------------------------------------------------------------------
The World War II 16 EVENT
American 62 NORP
George S. Patton 87 PERSON
----------------------------------------------------------------------------------------------------
one 38 CARDINAL
American 83 NORP
----------------------------------------------------------------------------------------------------
Pennsylvanians 32 NORP
the East Coast 157 LOC
the United States 178 GPE
----------------------------------------------------------------------------------------------------
1183 4 DATE
Henry II's 26 PERSON
three 32 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Paris 35 GPE
----------------------------------------------------------------------------------------------------
Communist 95 NORP
----------------------------------------------------------------------------------------------------
Spartacus 19 ORG
Roman Republic 78 GPE
----------------------------------------------------------------------------------------------------
Mediterranean 41 LOC
----------------------------------------------------------------------------------------------------
French 8 NORP
Hiroshima 54 GPE
Japanese 92 NORP
----------------------------------------------------------------------------------------------------
Egyptian 18 NORP
Hebrew 66 LANGUAGE
----------------------------------------------------------------------------------------------------
Comanches 89 NORP
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
Bible 53 WORK_OF_ART
----------------------------------------------------------------------------------------------------
noon 149 TIME
up years ago 202 DATE
----------------------------------------------------------------------------------------------------
two 68 CARDINAL
----------------------------------------------------------------------------------------------------
six foot 55 QUANTITY
----------------------------------------------------------------------------------------------------
Santa Claus 48 ORG
----------------------------------------------------------------------------------------------------
Nazi 42 NORP
South America 67 LOC
----------------------------------------------------------------------------------------------------
Philip Marlowe 32 PERSON
----------------------------------------------------------------------------------------------------
four-day 72 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Prince John 16 PERSON
Saxon 64 PERSON
Richard 87 PERSON
Saxon 106 ORG
----------------------------------------------------------------------------------------------------
two 30 CARDINAL
two 51 CARDINAL
----------------------------------------------------------------------------------------------------
Nick Charles 29 PERSON
Nora 55 PERSON
----------------------------------------------------------------------------------------------------
New York City 196 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Vampire Count Orlok 19 ORG
Hutter 86 PERSON
----------------------------------------------------------------------------------------------------
American 11 NORP
London 84 GPE
----------------------------------------------------------------------------------------------------
Kashmiri 10 ORG
Pakistani 44 NORP
Pakistan 85 GPE
the Indo-Pakistan War 114 FAC
1971 122 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Death of a Salesman 64 WORK_OF_ART
----------------------------------------------------------------------------------------------------
Belgium 28 GPE
the British Commonwealth 54 GPE
Empire 65 GPE
France 77 GPE
the German Army 111 ORG
World War II 164 EVENT
----------------------------------------------------------------------------------------------------
Seven 5 CARDINAL
----------------------------------------------------------------------------------------------------
African-American 46 NORP
NASA 93 ORG
the early years 116 DATE
U.S. 128 GPE
----------------------------------------------------------------------------------------------------
Paddington 10 PERSON
Ben Whishaw 23 PERSON
Brown 60 PERSON
Imelda Staunton's 208 PERSON
100th 215 ORDINAL
----------------------------------------------------------------------------------------------------
Indian 68 NORP
----------------------------------------------------------------------------------------------------
Kubo 22 ORG
----------------------------------------------------------------------------------------------------
Mahendra Singh Dhoni's 42 PERSON
the Indian Cricket Team 151 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
post-World War II Denmark 28 EVENT
German 53 NORP
thousands 99 CARDINAL
Danish 141 NORP
----------------------------------------------------------------------------------------------------
Imperial 27 ORG
the Rebel Alliance 62 ORG
the Death Star 116 PRODUCT
----------------------------------------------------------------------------------------------------
Avengers 37 ORG
Captain America 84 LOC
Iron Man 97 PERSON
----------------------------------------------------------------------------------------------------
Wyoming 24 GPE
winter 31 DATE
----------------------------------------------------------------------------------------------------
March 8 DATE
March 84 DATE
four 99 CARDINAL
----------------------------------------------------------------------------------------------------
Vincent van Gogh 112 PERSON
Robert Gulaczyk 129 PERSON
----------------------------------------------------------------------------------------------------
U.K. 4 GPE
the National Union of Mineworkers 103 ORG
the summer of 1984 125 DATE
----------------------------------------------------------------------------------------------------
Louis Bloom 16 PERSON
L.A. 78 GPE
----------------------------------------------------------------------------------------------------
Jep Gambardella 15 PERSON
Rome 72 GPE
decades 84 DATE
65th 104 ORDINAL
Jep 144 PERSON
----------------------------------------------------------------------------------------------------
Mumbai 29 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Baymax 66 PRODUCT
Hiro Hamada 90 PERSON
----------------------------------------------------------------------------------------------------
the age of 21 16 DATE
Tim 21 PERSON
----------------------------------------------------------------------------------------------------
English 166 LANGUAGE
----------------------------------------------------------------------------------------------------
Jiro Horikoshi 36 PERSON
Japanese 67 NORP
World War II 102 EVENT
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
New England 45 LOC
----------------------------------------------------------------------------------------------------
Hiccup 11 PERSON
Toothless 25 PERSON
hundreds 71 CARDINAL
Dragon Rider 123 PERSON
two 132 CARDINAL
----------------------------------------------------------------------------------------------------
2006-2007 12 DATE
US 52 GPE
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Mikael Blomkvist 27 PERSON
forty years 99 DATE
Lisbeth Salander 119 PERSON
----------------------------------------------------------------------------------------------------
Richard Phillips 42 PERSON
2009 55 DATE
Somali 75 NORP
Maersk Alabama 121 PERSON
first 132 ORDINAL
American 141 NORP
two hundred years 188 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
NWA 17 ORG
Compton 58 ORG
Los Angeles 73 GPE
California 85 GPE
the mid-1980s 103 DATE
Hip Hop 130 PERSON
----------------------------------------------------------------------------------------------------
Jimmy Hoffa 71 PERSON
1950-70s 93 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
one 107 CARDINAL
----------------------------------------------------------------------------------------------------
Bilbo Baggins 37 ORG
Gandalf the Grey 58 ORG
Erebor 98 ORG
Smaug 126 GPE
Bilbo Baggins 141 PERSON
----------------------------------------------------------------------------------------------------
Germany 64 GPE
the years 81 DATE
World War I 100 EVENT
----------------------------------------------------------------------------------------------------
forty years 120 DATE
----------------------------------------------------------------------------------------------------
James Bond's 12 PERSON
007 107 CARDINAL
----------------------------------------------------------------------------------------------------
7 14 CARDINAL
1968 97 DATE
Chicago 139 GPE
Illinois 149 GPE
----------------------------------------------------------------------------------------------------
Four 4 CARDINAL
daily 52 DATE
----------------------------------------------------------------------------------------------------
Micky Ward 32 PERSON
----------------------------------------------------------------------------------------------------
CIA 13 ORG
Europe 41 LOC
Paris 150 GPE
----------------------------------------------------------------------------------------------------
Bruno 34 PERSON
eight-year-old 54 DATE
German 88 NORP
Jewish 145 NORP
----------------------------------------------------------------------------------------------------
their eventful week 76 DATE
Dublin 86 GPE
----------------------------------------------------------------------------------------------------
Hobbit 18 ORG
Bilbo Baggins 33 PERSON
the Lonely Mountain 66 LOC
Smaug 176 GPE
----------------------------------------------------------------------------------------------------
Turkish 9 NORP
Istanbul 33 GPE
----------------------------------------------------------------------------------------------------
Thirteen-year-old 17 DATE
Briony Tallis 48 PERSON
----------------------------------------------------------------------------------------------------
Hollywood 22 GPE
----------------------------------------------------------------------------------------------------
New York City 24 GPE
Harlem 65 LOC
Frank Lucas 87 PERSON
----------------------------------------------------------------------------------------------------
Marine 19 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Mayan 12 NORP
----------------------------------------------------------------------------------------------------
VW 121 ORG
----------------------------------------------------------------------------------------------------
London 16 GPE
----------------------------------------------------------------------------------------------------
Benjamin Button 34 PERSON
----------------------------------------------------------------------------------------------------
Veer-Zaara 10 FAC
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Elizabeth Bennet 41 PERSON
Darcy 81 PERSON
Darcy 96 PERSON
----------------------------------------------------------------------------------------------------
New Zealander Burt Munro 37 LOC
years 54 DATE
1920 72 DATE
Indian 79 NORP
Utah 148 GPE
Bonneville Salt Flats 172 PERSON
1967 180 DATE
----------------------------------------------------------------------------------------------------
Serenity 29 ORG
----------------------------------------------------------------------------------------------------
Johnny Cash's 49 PERSON
Arkansas 90 GPE
Sun Records 139 ORG
Memphis 150 GPE
Elvis Presley 193 PERSON
Jerry Lee Lewis 210 PERSON
Carl Perkins 228 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Che Guevara 55 PERSON
----------------------------------------------------------------------------------------------------
Sixteen-year-old 16 DATE
Lilja 22 PERSON
Volodja 65 PERSON
Russia 81 GPE
One day 123 DATE
Lilja 130 PERSON
Andrej 156 PERSON
Sweden 180 GPE
Lilja 199 PERSON
----------------------------------------------------------------------------------------------------
the Tour de France, 57 ORG
Bruno 98 PERSON
the Belleville Sisters 134 ORG
the days 177 DATE
Fred Astaire 193 PERSON
----------------------------------------------------------------------------------------------------
the North/South Korean 51 ORG
2 71 CARDINAL
North Korean 84 NORP
Swiss 115 NORP
Swedish 123 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
African-American 52 NORP
their first season 105 DATE
----------------------------------------------------------------------------------------------------
Chinese 15 NORP
----------------------------------------------------------------------------------------------------
second 86 ORDINAL
Manuela 151 PERSON
----------------------------------------------------------------------------------------------------
FedEx 7 ORG
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
Irish Catholic 18 NORP
Boston 65 GPE
----------------------------------------------------------------------------------------------------
60 Minutes 105 TIME
Big Tobacco 127 ORG
----------------------------------------------------------------------------------------------------
Homer Hickam 30 PERSON
first 80 ORDINAL
Sputnik 88 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
seventeen-year-old 20 DATE
R.M.S. Titanic 120 ORG
----------------------------------------------------------------------------------------------------
Nishi 5 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Edward D. Wood Jr. 56 PERSON
----------------------------------------------------------------------------------------------------
Midwestern 33 NORP
----------------------------------------------------------------------------------------------------
Tombstone 62 GPE
Arizona 71 GPE
----------------------------------------------------------------------------------------------------
the summer of 1962 21 DATE
----------------------------------------------------------------------------------------------------
the years 61 DATE
World War II 88 EVENT
----------------------------------------------------------------------------------------------------
two 21 CARDINAL
----------------------------------------------------------------------------------------------------
Richard Kimble 18 PERSON
U.S. 155 GPE
----------------------------------------------------------------------------------------------------
Bronx 77 GPE
the 1960s 90 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
5 17 CARDINAL
5 44 CARDINAL
American 53 NORP
European 66 NORP
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
about two 30 CARDINAL
one 51 CARDINAL
Poland 68 GPE
France 89 GPE
----------------------------------------------------------------------------------------------------
three 26 CARDINAL
Crenshaw 61 PERSON
Los Angeles 83 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
many years ago 54 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Robert Gould Shaw 17 PERSON
the U.S. Civil War's 44 ORG
first 50 ORDINAL
Union Army 128 ORG
Confederates 150 NORP
----------------------------------------------------------------------------------------------------
one 36 CARDINAL
----------------------------------------------------------------------------------------------------
2015 19 DATE
Marty McFly 32 PERSON
1955 62 DATE
1985 100 DATE
first 137 ORDINAL
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
Mississippi 68 GPE
----------------------------------------------------------------------------------------------------
Central American 54 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Principal 94 PERSON
----------------------------------------------------------------------------------------------------

Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
Goonies 43 ORG
----------------------------------------------------------------------------------------------------
Southern 16 NORP
four decades 120 DATE
----------------------------------------------------------------------------------------------------
Five 4 CARDINAL
Saturday 42 DATE
----------------------------------------------------------------------------------------------------
Cambodia 35 GPE
Pol Pot's 59 PERSON
two million 137 CARDINAL
----------------------------------------------------------------------------------------------------
Three 5 CARDINAL
----------------------------------------------------------------------------------------------------
Mercury 33 ORG
7 35 CARDINAL
----------------------------------------------------------------------------------------------------
Rupert Pupkin 13 PERSON
----------------------------------------------------------------------------------------------------
Earth 74 LOC
----------------------------------------------------------------------------------------------------
Ted Kramer's 12 PERSON
Ted 85 PERSON
Billy 104 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Missouri 8 GPE
Josey Wales 27 PERSON
Confederate 47 ORG
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
British 11 NORP
Kings 64 ORG
Kafiristan 78 GPE
Alexander the Great 144 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Jackal 41 WORK_OF_ART
Charles de Gaulle 74 PERSON
France 99 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Weimar Republic 51 GPE
Berlin 62 GPE
two 75 CARDINAL
the Nazi Party 100 ORG
----------------------------------------------------------------------------------------------------
one 32 CARDINAL
five 44 CARDINAL
Willy Wonka's 113 WORK_OF_ART
----------------------------------------------------------------------------------------------------
Texas 34 GPE
New York City 51 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
African-American 95 NORP
----------------------------------------------------------------------------------------------------
Bonnie Parker 28 PERSON
Clyde Barrow 76 PERSON
----------------------------------------------------------------------------------------------------
Snobbish 8 NORP
Henry Higgins 42 PERSON
Eliza Doolittle 105 PERSON
----------------------------------------------------------------------------------------------------
turn of the century 22 DATE
London 29 GPE
two 86 CARDINAL
----------------------------------------------------------------------------------------------------
D-Day 19 DATE
Allied 63 ORG
German 74 NORP
----------------------------------------------------------------------------------------------------
two 41 CARDINAL
----------------------------------------------------------------------------------------------------
two 25 CARDINAL
----------------------------------------------------------------------------------------------------
American 138 NORP
Italy 216 GPE
----------------------------------------------------------------------------------------------------
Dunson 6 PERSON
14 years 61 DATE
Missouri 101 GPE
----------------------------------------------------------------------------------------------------
two 113 CARDINAL
----------------------------------------------------------------------------------------------------
World War II 19 EVENT
American 29 NORP
Harry Morgan 53 PERSON
French 78 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Merry Widow 135 WORK_OF_ART
----------------------------------------------------------------------------------------------------
Geronimo 100 NORP
----------------------------------------------------------------------------------------------------
Europe 38 LOC
----------------------------------------------------------------------------------------------------
$1 million 35 MONEY
Baby 166 PERSON
----------------------------------------------------------------------------------------------------
Mary Shelley 12 PERSON
Frankenstein 80 PERSON
----------------------------------------------------------------------------------------------------
Rufus T. Firefly 16 PERSON
Freedonia 66 GPE
Sylvania 107 GPE
Teasdale 146 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Frankenstein 16 PERSON
----------------------------------------------------------------------------------------------------
Mexico City 65 GPE
the early 1970s 84 DATE
----------------------------------------------------------------------------------------------------
Yorkshire 17 PERSON
Johnny Saxby 44 PERSON
Romanian 141 NORP
season 175 DATE
Johnny 224 PERSON
----------------------------------------------------------------------------------------------------
Wilson 41 PERSON
a.k.a 48 GPE
----------------------------------------------------------------------------------------------------
FBI 29 ORG
Wyoming Native 95 GPE
----------------------------------------------------------------------------------------------------
African-American 24 NORP
the weekend 78 DATE
----------------------------------------------------------------------------------------------------
Ethan Hunt 10 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Deacon 13 ORG
Vladislav 27 ORG
----------------------------------------------------------------------------------------------------
Anna 19 PERSON
Japanese 95 NORP
Marnie 163 PERSON
Marnie 201 PERSON
----------------------------------------------------------------------------------------------------
Stephen Hawking 71 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
Amsterdam 99 GPE
----------------------------------------------------------------------------------------------------
Greg 18 PERSON
Earl 105 PERSON
----------------------------------------------------------------------------------------------------
Broadway 114 FAC
----------------------------------------------------------------------------------------------------
Iranian 10 NORP
French 33 NORP
two 50 CARDINAL
----------------------------------------------------------------------------------------------------
Emma 43 PERSON
----------------------------------------------------------------------------------------------------
Three 5 CARDINAL
India 33 GPE
the turn of the millennium 63 DATE
----------------------------------------------------------------------------------------------------
first 38 ORDINAL
----------------------------------------------------------------------------------------------------
Forky 28 PERSON
Woody 41 PERSON
----------------------------------------------------------------------------------------------------
Steve Rogers 15 PERSON
Avenger 100 NORP
Black Widow 135 PERSON
----------------------------------------------------------------------------------------------------
Janardhan Jakhar 16 PERSON
Heer 103 PERSON
----------------------------------------------------------------------------------------------------
Montana 57 GPE
Nebraska 69 GPE
million-dollar 127 MONEY
Mega Sweepstakes Marketing 154 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Aviator 120 ORG
the Little Prince 226 FAC
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Paris 24 GPE
----------------------------------------------------------------------------------------------------
LEGO 153 ORG
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
Kirk 117 PERSON
one 170 CARDINAL
----------------------------------------------------------------------------------------------------
Agu 39 PERSON
African 104 NORP
----------------------------------------------------------------------------------------------------
Harvard 10 ORG
Mark Zuckerberg 34 PERSON
----------------------------------------------------------------------------------------------------
the 1960s 12 DATE
Charles Xavier 48 PERSON
Erik Lensherr 66 PERSON
Erik 115 PERSON
----------------------------------------------------------------------------------------------------
Three 5 CARDINAL
Las Vegas 56 GPE
the previous night 94 TIME
----------------------------------------------------------------------------------------------------
Pat Solitano 66 PERSON
Pat 175 PERSON
Tiffany 189 GPE
----------------------------------------------------------------------------------------------------
Hollywood 37 GPE
CIA 100 ORG
six 151 CARDINAL
Americans 161 NORP
Tehran 171 GPE
U.S. 187 GPE
Iran 210 GPE
1979 218 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Harry 8 PERSON
Ron 13 PERSON
Horcruxes 79 ORG
three 120 CARDINAL
----------------------------------------------------------------------------------------------------
five-year-old 15 DATE
Ponyo 54 GPE
----------------------------------------------------------------------------------------------------

post-Watergate 42 EVENT
British 80 NORP
David Frost 107 PERSON
Richard Nixon 142 PERSON
----------------------------------------------------------------------------------------------------
Paprika 142 PERSON
----------------------------------------------------------------------------------------------------
Christine Collins 39 PERSON
Angelina Jolie 55 PERSON
L.A.P.D. 78 GPE
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
eighth 10 ORDINAL
----------------------------------------------------------------------------------------------------
Makoto 31 PERSON
----------------------------------------------------------------------------------------------------
two 32 CARDINAL
Light Yagami 72 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
A.I. 172 GPE
----------------------------------------------------------------------------------------------------
India 34 GPE
Copenhagen 56 ORG
Denmark 65 GPE
----------------------------------------------------------------------------------------------------
Idi Amin's 61 PERSON
the 1970s 119 DATE
----------------------------------------------------------------------------------------------------
the late 1960s 17 DATE
San Francisco 46 GPE
the Zodiac Killer 132 FAC
Northern California 195 LOC
----------------------------------------------------------------------------------------------------
two 86 CARDINAL
Detective Brikowski 176 PERSON
Goodkat 197 PERSON
----------------------------------------------------------------------------------------------------
December 1914 16 DATE
the Western Front 68 ORG
the First World War 127 EVENT
----------------------------------------------------------------------------------------------------
Ian Curtis 23 PERSON
Joy Division 61 ORG
the age of 23 156 DATE
----------------------------------------------------------------------------------------------------
Rapunzel 34 GPE
first 173 ORDINAL
----------------------------------------------------------------------------------------------------
Nazi 11 NORP
Netherlands 32 GPE
World War II 52 EVENT
Jewish 62 NORP
Gestapo 102 PERSON
Dutch 129 NORP
----------------------------------------------------------------------------------------------------
Ennis 5 ORG
Jack 14 PERSON
two 22 CARDINAL
----------------------------------------------------------------------------------------------------
Yuma 99 GPE
----------------------------------------------------------------------------------------------------
Los Angeles 11 GPE
----------------------------------------------------------------------------------------------------
Shanghai 11 GPE
China 18 GPE
the 1940s 31 DATE
Axe Gang 91 WORK_OF_ART
----------------------------------------------------------------------------------------------------
Jason Bourne 17 PERSON
CIA 37 ORG
----------------------------------------------------------------------------------------------------
a year 47 DATE
----------------------------------------------------------------------------------------------------
Ray Charles 87 PERSON
South 128 LOC
age seven 162 DATE
the 1950s and 1960s 222 DATE
----------------------------------------------------------------------------------------------------
Tokyo 98 GPE
----------------------------------------------------------------------------------------------------
Harry Potter 12 PERSON
----------------------------------------------------------------------------------------------------
Mexico City 14 GPE
CIA 28 ORG
----------------------------------------------------------------------------------------------------
11-year-old 26 DATE
----------------------------------------------------------------------------------------------------
American 11 NORP
Samurai 49 GPE
----------------------------------------------------------------------------------------------------
Three 5 CARDINAL
Irish 17 NORP
----------------------------------------------------------------------------------------------------
1990 7 DATE
East Germany 156 GPE
----------------------------------------------------------------------------------------------------
Irish 17 NORP
----------------------------------------------------------------------------------------------------
7-year-old 63 DATE
----------------------------------------------------------------------------------------------------
'The Orchid Thief' 91 WORK_OF_ART
Susan Orlean 107 PERSON
----------------------------------------------------------------------------------------------------
160 3 CARDINAL
U.S. 14 GPE
Somalia 41 GPE
two 56 CARDINAL
Somalis 180 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
two weeks 13 DATE
20 17 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
East Berlin 48 GPE
U.S. 63 GPE
----------------------------------------------------------------------------------------------------
Danny Ocean 11 PERSON
ten 23 CARDINAL
three 53 CARDINAL
Las Vegas 63 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
the 1930s 34 DATE
three 41 CARDINAL
----------------------------------------------------------------------------------------------------
Neal Oliver 11 PERSON
I60 100 LAW
----------------------------------------------------------------------------------------------------
Stan Marsh 15 PERSON
Canada 111 GPE
----------------------------------------------------------------------------------------------------
Three 5 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
first 29 ORDINAL
Los Angeles 50 GPE
----------------------------------------------------------------------------------------------------
Rushmore Preparatory School 55 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
John Malkovich 94 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Zorg 145 PERSON
----------------------------------------------------------------------------------------------------
weekly 27 DATE
Pierre 81 PERSON
----------------------------------------------------------------------------------------------------
FBI 6 ORG
----------------------------------------------------------------------------------------------------
David Helfgott 22 PERSON
Years later 87 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Hamlet 6 ORG
Denmark 25 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Hong Kong 14 GPE
----------------------------------------------------------------------------------------------------
Italian 16 NORP
Beatrice 134 ORG
----------------------------------------------------------------------------------------------------
two 25 CARDINAL
Dante 56 PERSON
Randal 67 PERSON
----------------------------------------------------------------------------------------------------
Los Angeles 52 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Muppet 10 NORP
Christmas Eve 117 DATE
----------------------------------------------------------------------------------------------------
Black Nationalist 72 ORG
Islam 188 NORP
----------------------------------------------------------------------------------------------------
Three 5 CARDINAL
British 49 NORP
French 84 NORP
Indian War 99 EVENT
----------------------------------------------------------------------------------------------------
1930s 8 DATE
Italy 14 GPE
World War 35 EVENT
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Daniel Kaffee 40 PERSON
Marines 56 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
New York 19 GPE
California 55 GPE
Hollywood 124 GPE
----------------------------------------------------------------------------------------------------
Tom Reagan 10 PERSON
Prohibition-era 43 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Rex 3 PERSON
Saskia 14 ORG
Saskia 103 ORG
three years 134 DATE
Rex 161 PERSON
----------------------------------------------------------------------------------------------------
1969 7 DATE
two 12 CARDINAL
----------------------------------------------------------------------------------------------------
China 39 GPE
----------------------------------------------------------------------------------------------------
English 15 LANGUAGE
Japanese 55 NORP
China 75 GPE
World War II 95 EVENT
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
New Jersey 13 GPE
1935 21 DATE
----------------------------------------------------------------------------------------------------
that evening 122 TIME
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Enterprise 37 ORG
Kirk 56 PERSON
Khan Noonien Singh 101 PERSON
----------------------------------------------------------------------------------------------------
Green Beret 21 PERSON
one 121 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Fifteen years 13 DATE
Halloween night 59 TIME
1963 64 DATE
Michael Myers 79 PERSON
Haddonfield 155 GPE
Illinois 165 GPE
----------------------------------------------------------------------------------------------------
Paris 26 GPE
----------------------------------------------------------------------------------------------------
Russia 17 GPE
Napoleon 101 ORG
----------------------------------------------------------------------------------------------------
New York 11 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
New York 18 GPE
Frank Serpico 42 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
the Cahulawassee River 39 LOC
Lewis Medlock 112 PERSON
American 198 NORP
----------------------------------------------------------------------------------------------------
NYC 13 ORG
the Narcotics Bureau 42 ORG
French 90 NORP
----------------------------------------------------------------------------------------------------
Scorpio Killer 49 PRODUCT
San Francisco Police Inspector 114 ORG
Harry Callahan 137 PERSON
----------------------------------------------------------------------------------------------------
Allied 6 ORG
Nazis 61 NORP
American 82 NORP
George Carnaby 115 PERSON
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
World War II 19 EVENT
U.S. Army Major 49 ORG
a dozen 69 CARDINAL
German 156 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Thomas 23 PERSON
the Roman Catholic Church 110 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
British 19 NORP
Zulu 48 PERSON
Rorke's Drift 74 ORG
----------------------------------------------------------------------------------------------------
James Bond 58 PERSON
Fort Knox 103 EVENT
----------------------------------------------------------------------------------------------------
San Francisco 23 GPE
Northern California 94 LOC
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Seven 5 CARDINAL
Mexican 38 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Five 4 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
American 18 NORP
Ireland 71 GPE
----------------------------------------------------------------------------------------------------
Earth 44 LOC
----------------------------------------------------------------------------------------------------
WWI Africa 13 GPE
----------------------------------------------------------------------------------------------------
Buenos Aires 52 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
the final years 99 DATE
Hollywood 112 GPE
1969 133 DATE
Los Angeles 145 GPE
----------------------------------------------------------------------------------------------------
one 94 CARDINAL
----------------------------------------------------------------------------------------------------
one summer 19 DATE
six-year-old 61 DATE
Moonee 68 PERSON
Walt Disney World 233 ORG
----------------------------------------------------------------------------------------------------
Bryan Stevenson 60 PERSON
----------------------------------------------------------------------------------------------------
Frank 5 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Spanish 15 NORP
Berlin 54 GPE
----------------------------------------------------------------------------------------------------
Guardians 13 NORP
Star-Lord's 118 ORG
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
the Granite Mountain Hotshots 56 ORG
----------------------------------------------------------------------------------------------------
the Cold War 19 EVENT
American 32 NORP
Soviet 81 NORP
CIA 117 ORG
Soviet 166 NORP
American 184 NORP
Francis Gary Powers 224 PERSON
----------------------------------------------------------------------------------------------------
Incredibles 15 ORG
Bob Parr 95 PERSON
Incredible 111 PERSON
----------------------------------------------------------------------------------------------------
Ancient Polynesia 20 PERSON
Demigod Maui 72 GPE
Moana 86 PERSON
Ocean 118 LOC
Demigod 149 PERSON
----------------------------------------------------------------------------------------------------
FBI 17 ORG
U.S. 141 GPE
Mexico 152 GPE
----------------------------------------------------------------------------------------------------
World Heavyweight Champion 37 EVENT
Rocky Balboa 50 PERSON
Adonis Johnson 99 PERSON
Apollo Creed 157 PERSON
----------------------------------------------------------------------------------------------------
Russian 12 NORP
----------------------------------------------------------------------------------------------------
West Texas 127 LOC
----------------------------------------------------------------------------------------------------
her decades ago 126 DATE
----------------------------------------------------------------------------------------------------
Caesar 58 ORG
a decade earlier 153 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
S.W.A.T. 10 NORP
----------------------------------------------------------------------------------------------------
daily 51 DATE
two 64 CARDINAL
LA 92 GPE
----------------------------------------------------------------------------------------------------
Clock 9 ORG
four-inch 30 QUANTITY
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
U.S. 52 GPE
----------------------------------------------------------------------------------------------------
two 16 CARDINAL
Danish 23 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
27-year-old 60 DATE
----------------------------------------------------------------------------------------------------
Dave Lizewski 13 PERSON
one day 80 DATE
----------------------------------------------------------------------------------------------------
two 16 CARDINAL
----------------------------------------------------------------------------------------------------
Oakland A's 11 ORG
Billy Beane's 41 PERSON
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Ohio 48 GPE
Twinkie 100 PERSON
America 212 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Watson 57 PERSON
England 150 GPE
----------------------------------------------------------------------------------------------------
Michael Oher 25 PERSON
first 110 ORDINAL
NFL 120 ORG
----------------------------------------------------------------------------------------------------

seven 116 CARDINAL
----------------------------------------------------------------------------------------------------
Russian 128 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
Boston 10 GPE
----------------------------------------------------------------------------------------------------
French 27 NORP
Édith Piaf 45 PERSON
the age of 19 155 DATE
----------------------------------------------------------------------------------------------------
Chinese Martial Arts 35 ORG
Huo Yuanjia 54 PERSON
the Jin Wu Sports Federation 125 ORG
----------------------------------------------------------------------------------------------------
Vienna 29 GPE
----------------------------------------------------------------------------------------------------
years ago 129 DATE
----------------------------------------------------------------------------------------------------
Harry Potter 15 PERSON
sixth year 37 DATE
Hogwarts 49 ORG
Voldemort 171 PERSON
----------------------------------------------------------------------------------------------------
Sparta 23 GPE
300 42 CARDINAL
Persians 65 NORP
480 87 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
1985 7 DATE
----------------------------------------------------------------------------------------------------
INTERPOL 86 ORG
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
New York City 121 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
World War One 140 EVENT
----------------------------------------------------------------------------------------------------
New Jersey 77 GPE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
J.M. Barrie's 30 PERSON
Peter Pan 92 PERSON
----------------------------------------------------------------------------------------------------
DEA 19 ORG
New York 39 GPE
Montgomery Brogan 69 PERSON
24 remaining hours 116 TIME
seven-year 143 DATE
----------------------------------------------------------------------------------------------------
Evan Treborn 12 PERSON
----------------------------------------------------------------------------------------------------
Four weeks 10 DATE
UK 72 GPE
----------------------------------------------------------------------------------------------------
Japanese 27 NORP
ninth 64 ORDINAL
Battle Royale 153 WORK_OF_ART
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Mexico 9 GPE
two 14 CARDINAL
two 104 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
two 63 CARDINAL
----------------------------------------------------------------------------------------------------
George Jung 28 PERSON
Pablo Escobar 84 PERSON
American 110 NORP
the 1970s 138 DATE
the United States 159 GPE
----------------------------------------------------------------------------------------------------
Russian 9 NORP
German 22 NORP
the Battle of Stalingrad 90 FAC
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
New York City 23 GPE
Patrick Bateman 69 PERSON
----------------------------------------------------------------------------------------------------
Lola 36 PERSON
20 minutes 51 TIME
100,000 75 CARDINAL
----------------------------------------------------------------------------------------------------
1962 48 DATE
the second World War 123 EVENT
----------------------------------------------------------------------------------------------------
China 109 GPE
heroines 129 CARDINAL
----------------------------------------------------------------------------------------------------
Las Vegas 69 GPE
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Thirteen years later 133 DATE
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
Dashwood 17 PERSON
second 42 ORDINAL
three 61 CARDINAL
two 113 CARDINAL
----------------------------------------------------------------------------------------------------
John McClane 12 PERSON
Harlem 25 LOC
German 60 NORP
New York City 93 GPE
the Federal Reserve Building 145 ORG
----------------------------------------------------------------------------------------------------
William Blake 58 PERSON
American 99 NORP
----------------------------------------------------------------------------------------------------
Robert Kincaid 27 PERSON
Francesca Johnson 80 PERSON
four days 94 DATE
the 1960s 107 DATE
----------------------------------------------------------------------------------------------------
NASA 4 ORG
Apollo 44 ORG
Earth 56 LOC
three 149 CARDINAL
----------------------------------------------------------------------------------------------------
Polish 37 NORP
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
the last day 70 DATE
May 1976 92 DATE
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
New Yorkers 15 NORP
Alabama 50 GPE
one 109 CARDINAL
----------------------------------------------------------------------------------------------------
twenty-seven-year-old 23 DATE
Tokyo 111 GPE
----------------------------------------------------------------------------------------------------
eight-year-old 17 DATE
Christmas 148 DATE
----------------------------------------------------------------------------------------------------
Michael Corleone 24 PERSON
60s 40 DATE
----------------------------------------------------------------------------------------------------
Harry 5 PERSON
Sally 15 PERSON
years 47 DATE
----------------------------------------------------------------------------------------------------
Faustian 35 NORP
----------------------------------------------------------------------------------------------------
Elizabeth II 96 PERSON
----------------------------------------------------------------------------------------------------
Thanksgiving 51 DATE
----------------------------------------------------------------------------------------------------
Two 3 CARDINAL
----------------------------------------------------------------------------------------------------
Texas 37 GPE
one 60 CARDINAL
----------------------------------------------------------------------------------------------------
Norman 6 PERSON
Chelsea 79 PERSON
Golden Pond 95 ORG
Billy 149 PERSON
Chelsea 169 PERSON
----------------------------------------------------------------------------------------------------
Australian 34 NORP
----------------------------------------------------------------------------------------------------
New York City 82 GPE
----------------------------------------------------------------------------------------------------
Kermit 6 ORG
America 51 GPE
Hollywood 80 GPE
Kermit 122 ORG
----------------------------------------------------------------------------------------------------
Alcatraz 8 FAC
three 111 CARDINAL
one 178 CARDINAL
----------------------------------------------------------------------------------------------------
Hazel 108 PERSON
Fiver 118 ORG
----------------------------------------------------------------------------------------------------
Roy Neary 9 PERSON
----------------------------------------------------------------------------------------------------
Philip Marlowe 35 PERSON
----------------------------------------------------------------------------------------------------
I.R.A. 31 NORP
the Mexican Revolution 122 EVENT
----------------------------------------------------------------------------------------------------
U.S. 15 GPE
Nazi 95 NORP
----------------------------------------------------------------------------------------------------
Panther 20 PERSON
----------------------------------------------------------------------------------------------------
two 8 CARDINAL
Paul McCartney 111 PERSON
----------------------------------------------------------------------------------------------------
New York 16 GPE
----------------------------------------------------------------------------------------------------
Texas 43 GPE
----------------------------------------------------------------------------------------------------
Hawaii 9 GPE
1941 17 DATE
second 119 ORDINAL
----------------------------------------------------------------------------------------------------
World War II 62 EVENT
----------------------------------------------------------------------------------------------------
London 15 GPE
----------------------------------------------------------------------------------------------------

In [172]:
#classer les phrases par rapport à leurs positivités 

import spacy
from spacytextblob.spacytextblob import SpacyTextBlob

nlp = spacy.load('en_core_web_sm')
nlp.add_pipe('spacytextblob')
text = 'fuck you asshole'


doc = nlp(text)


doc._.polarity      # Polarity: -0.125
#doc._.subjectivity  # Sujectivity: 0.9
#doc._.assessments   # Assessments: [(['really', 'horrible'], -1.0, 1.0, None), (['worst', '!'], -1.0, 1.0, None), (['really', 'good'], 0.7, 0.6000000000000001, None), (['happy'], 0.8, 1.0, None)]

-0.4

In [170]:
import spacy
from spacytextblob.spacytextblob import SpacyTextBlob

nlp = spacy.load('en_core_web_sm')
nlp.add_pipe('spacytextblob')

for i in list(df.values):
    
    doc = nlp(i[8])

    if doc._.polarity > 0.7:
        print(f'Titre : {i[1]}\nSynopsis : {i[8]}\nNote polarity : {doc._.polarity}\n','-'*100)

Titre : Les Aventuriers de l'arche perdue
Synopsis : In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before Adolf Hitler's Nazis can obtain its awesome powers.
Note polarity : 1.0
 ----------------------------------------------------------------------------------------------------
Titre : Swades: Nous, le peuple
Synopsis : A successful Indian scientist returns to an Indian village to take his nanny to America with him and in the process rediscovers his roots.
Note polarity : 0.75
 ----------------------------------------------------------------------------------------------------
Titre : Le Monde de Nemo
Synopsis : After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.
Note polarity : 0.8
 ----------------------------------------------------------------------------------------------------
Titre : Procès de singe
Synopsis : Based on a real-life case in 1925, two great lawyers argue the case for and against a science teacher accused of the crime of teaching evolution.
Note polarity : 0.8
 ----------------------------------------------------------------------------------------------------
Titre : Blood Diamond
Synopsis : A fisherman, a smuggler, and a syndicate of businessmen match wits over the possession of a priceless diamond.
Note polarity : 1.0
 ----------------------------------------------------------------------------------------------------
Titre : Les diaboliques
Synopsis : The wife and mistress of a loathed school principal plan to murder him with what they believe is the perfect alibi.
Note polarity : 1.0
 ----------------------------------------------------------------------------------------------------